CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  mode VARCHAR(255) NOT NULL,
  room_id UUID NOT NULL REFERENCES rooms(id),
  client_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data JSONB DEFAULT '{}'
);